# Generated by Django 6.0.3 on 2026-03-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ghost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
